language: python

python:
  - 3.3
  - 3.4
  - 3.6
  - 3.7
  - pypy
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install . -U

script:
  - python -m pytest tests.py