#!/usr/bin/env python
from tapeterm.tapeterm import *

if __name__ == "__main__":
    args = arg_parsing()
    json_file = JSON_EL[:]
    if args.language == 'en':
        json_file = JSON_EN[:]

    tp = TapeTerm(json_file=json_file, api_key=args.youtube_api_key, player=args.player)
    tp.disp_menu()
