# -*- coding: utf-8 -*-

def GetThem():
    return  {
                1:[u'Bob Marley','PLSRDGXudTSm_x9lRMuGbm6Mf-Gx8NfmfW','Reggae','','','','',''],
                2:[u'Summer Roots', 'PLSRDGXudTSm8YFJzLVX8Yk0ZcwxVdooai','Reggae','','','','',''],
                3:[u'Mad About You','PLSRDGXudTSm8x2vcosYPD1sqE3cnFVw8c','HipTripHop','','','','','',''],
                4:[u'Ηλεκτρικά Ξημερώματα', 'PLSRDGXudTSm9JVxz0KRPIKocBePENGI7M','Reading','Morning','','','',''],
                5:[u'Κεφάτα Πρωινά', 'PLSRDGXudTSm-T0SH2WcZ2lVxB6H1RVGnn', 'Popular','Morning','','','','',''],
                6:[u'Smoky Head','PLSRDGXudTSm8A9sBOvMcmCbG6VIUt2-Es', 'Rock','','','','','','',''],
                7:[u'Feeling Good','PLSRDGXudTSm-VAX1PRgL7cTgmcRnxt6Mq', 'Xaroumenes','Morning','','','','',''],
                8:[u'Πρωινό Στο Κρεβάτι','PLSRDGXudTSm9edl7Bha5Py6t0eM62kj8l','Morning','','','',''],
                9:[u'Make My Day','PLSRDGXudTSm9duWeggg_scs8XdnTmN_kE','Morning','','','',''],
                10:[u'Good Morning Sunshine ','PLSRDGXudTSm-jkPYsnTWugKfNSatNc8C_','Morning','','','',''],
                11:[u'Sunday Morning','PLSRDGXudTSm-Wj0T3QRbvvZpIVmyBW9gn','Morning','','','',''],
                12:[u'Γυμναστική','PLSRDGXudTSm8xskH84A8HmuqTo-ddGVwX','Morning','','','',''],
                13:[u'Mellow Morning','PLSRDGXudTSm_55t0DWCrcVNxX2AJDkm_f','Morning','','','',''],
                14:[u'Αγουροξυπνήματα','PLSRDGXudTSm8rOJ1ecbS1fdomXbNxdkI5','Morning','','','',''],
                15:[u'Καφές και βιβλία','PLSRDGXudTSm8gle58o1uoCgV3f1GPs0Iy','Morning','','','',''],
                16:[u'Morning Energy','PLSRDGXudTSm9hkkfPPC-NRiZh62VFMyOB','Morning','','','',''],
                17:[u'Coffee Time','PLSRDGXudTSm_dpRujR-T0I5OqLBHEuNem','Morning','','','',''],
                18:[u'Brunch','PLSRDGXudTSm9JIAf6KEkDsuPeeMxEwMi9','Morning','','','',''],
                19:[u'Μουσικές του Κόσμου','PLSRDGXudTSm9gBoLbXztA5M6a5qM3oyav','Morning','','','',''],
                20:[u'Λούνα Πάρκ','PLSRDGXudTSm-z5IlB1QE7kvR1m7kVlVI-','Morning','','','',''],
                21:[u'Cleaning','PLSRDGXudTSm_qMSnxgy8fZMVA1RVu5Q8Z','Morning','','','',''],
                22:[u'Home','PLSRDGXudTSm8N7b-RzOHzYRsHl8DKzDbS','Morning','','','',''],
                23:[u'Τα Ραδιοφωνικά','PLSRDGXudTSm_jSzrYHL_aW_TL-sdJAzSP','Morning','','','',''],
                24:[u'Τα Τζαζεμένα','PLSRDGXudTSm8nRhAaeO0Ichb6mvlMiS8V','Morning','','','',''],
                25:[u'Working Fridays','PLSRDGXudTSm8qW3nlYA_QO6Fv4nKrGpza','Morning','','','',''],
                26:[u'Jazz And Coffee','PLSRDGXudTSm9EDBMEFBXUXRaAA-TeGmgq','Morning','','','',''],
                27:[u'Blue Monday','PLSRDGXudTSm9EcBaBk0fk1oCqwb8gsLde','Morning','','','',''],
                28:[u'Run','PLSRDGXudTSm81lledAXOlUg_AGGPu8Unz','Morning','','','',''],
                29:[u'Ηλιόλουστες Μέρες','PLSRDGXudTSm_AtTbW-k7r6T1cfkVzYBRz','Morning','','','',''],
                30:[u'Να Μου Γελάς','PLSRDGXudTSm9O4-jYAvdW-sntf4zJyvxf','Morning','','','','',''],
                31:[u'Coffee Break','PLSRDGXudTSm8NNRMP-Vy0N5drxdgq4D-H','Morning','','','','',''],
                32:[u'Coffee House','PLSRDGXudTSm8SwpTaGkAQ5Jg5iL6Bm9ZI','Morning','','','','',''],
                33:[u'Bedtime Stories','PLSRDGXudTSm9gXGLpMVsH9OsCAVa0aSS4','Morning','','','','',''],
                34:[u'Gloomy Sunday','PLSRDGXudTSm-NQnuXT22HM24Gep-yqTn-','Morning','','','','',''],
                35:[u'Morning Coffee Mix','PLSRDGXudTSm9N0ftZUx7SYFqmglOACOzo','Morning','','','','',''],
                36:[u'','','','','','','',''],
                37:[u'','','','','','','',''],
                38:[u'','','','','','','',''],
                39:[u'','','','','','','',''],
                40:[u'','','','','','','',''],
                41:[u'','','','','','','',''],
                42:[u'','','','','','','',''],
                43:[u'','','','','','','',''],
                44:[u'','','','','','','',''],
                45:[u'','','','','','','',''],
                46:[u'','','','','','','',''],
                47:[u'','','','','','','',''],
                48:[u'','','','','','','',''],
                49:[u'','','','','','','',''],
                50:[u'','','','','','','',''],
                51:[u'','','','','','','',''],
                52:[u'','','','','','','',''],
                53:[u'','','','','','','',''],
                54:[u'','','','','','','',''],
                55:[u'','','','','','','',''],
                56:[u'','','','','','','',''],
                57:[u'','','','','','','',''],
                58:[u'','','','','','','',''],
                59:[u'','','','','','','',''],
                60:[u'','','','','','','',''],
                61:[u'','','','','','','',''],
                62:[u'','','','','','','',''],
                63:[u'','','','','','','',''],
                64:[u'','','','','','','',''],
                65:[u'','','','','','','',''],
                66:[u'','','','','','','',''],
                67:[u'','','','','','','',''],
                68:[u'','','','','','','',''],
                69:[u'','','','','','','',''],
                70:[u'','','','','','','',''],




            }
