# -*- coding: utf-8 -*-

def GetThem():
    return  {
                1:[u'Bob Marley','PLSRDGXudTSm_x9lRMuGbm6Mf-Gx8NfmfW','Reggae','','','','',''],
                2:[u'Summer Roots', 'PLSRDGXudTSm8YFJzLVX8Yk0ZcwxVdooai','Reggae','','','','',''],
                3:[u'Mad About You','PLSRDGXudTSm8x2vcosYPD1sqE3cnFVw8c','HipTripHop','','','','','',''],
                4:[u'Ηλεκτρικά Ξημερώματα', 'PLSRDGXudTSm9JVxz0KRPIKocBePENGI7M','Reading','Morning','','','',''],
                5:[u'Κεφάτα Πρωινά', 'PLSRDGXudTSm-T0SH2WcZ2lVxB6H1RVGnn', 'Popular','Morning','Xaroumenes','','','',''],
                6:[u'Smoky Head','PLSRDGXudTSm8A9sBOvMcmCbG6VIUt2-Es', 'Rock','','','','','','',''],
                7:[u'Feeling Good','PLSRDGXudTSm-VAX1PRgL7cTgmcRnxt6Mq', 'Xaroumenes','Morning','','','','',''],
                8:[u'Πρωινό Στο Κρεβάτι','PLSRDGXudTSm9edl7Bha5Py6t0eM62kj8l','Morning','Xalarwtikes','','',''],
                9:[u'Make My Day','PLSRDGXudTSm9duWeggg_scs8XdnTmN_kE','Morning','Xaroumenes','','',''],
                10:[u'Good Morning Sunshine ','PLSRDGXudTSm-jkPYsnTWugKfNSatNc8C_','Morning','','','',''],
                11:[u'Sunday Morning','PLSRDGXudTSm-Wj0T3QRbvvZpIVmyBW9gn','Morning','Xalarwtikes','','',''],
                12:[u'Γυμναστική','PLSRDGXudTSm8xskH84A8HmuqTo-ddGVwX','Morning','Xaroumenes','','',''],
                13:[u'Mellow Morning','PLSRDGXudTSm_55t0DWCrcVNxX2AJDkm_f','Morning','','','',''],
                14:[u'Αγουροξυπνήματα','PLSRDGXudTSm8rOJ1ecbS1fdomXbNxdkI5','Morning','Xaroumenes','','',''],
                15:[u'Καφές και βιβλία','PLSRDGXudTSm8gle58o1uoCgV3f1GPs0Iy','Morning','','','',''],
                16:[u'Morning Energy','PLSRDGXudTSm9hkkfPPC-NRiZh62VFMyOB','Morning','','','',''],
                17:[u'Coffee Time','PLSRDGXudTSm_dpRujR-T0I5OqLBHEuNem','Morning','XalarwtikesΦ','','',''],
                18:[u'Brunch','PLSRDGXudTSm9JIAf6KEkDsuPeeMxEwMi9','Morning','','','',''],
                19:[u'Μουσικές του Κόσμου','PLSRDGXudTSm9gBoLbXztA5M6a5qM3oyav','Morning','Xaroumenes','','',''],
                20:[u'Λούνα Πάρκ','PLSRDGXudTSm-z5IlB1QE7kvR1m7kVlVI-','Morning','','','',''],
                21:[u'Cleaning','PLSRDGXudTSm_qMSnxgy8fZMVA1RVu5Q8Z','Morning','Xaroumenes','','',''],
                22:[u'Home','PLSRDGXudTSm8N7b-RzOHzYRsHl8DKzDbS','Morning','Noon','','',''],
                23:[u'Τα Ραδιοφωνικά','PLSRDGXudTSm_jSzrYHL_aW_TL-sdJAzSP','Morning','','','',''],
                24:[u'Τα Τζαζεμένα','PLSRDGXudTSm8nRhAaeO0Ichb6mvlMiS8V','Morning','Xalarwtikes','','',''],
                25:[u'Working Fridays','PLSRDGXudTSm8qW3nlYA_QO6Fv4nKrGpza','Morning','','','',''],
                26:[u'Jazz And Coffee','PLSRDGXudTSm9EDBMEFBXUXRaAA-TeGmgq','Morning','','','',''],
                27:[u'Blue Monday','PLSRDGXudTSm9EcBaBk0fk1oCqwb8gsLde','Morning','Xalarwtikes','','',''],
                28:[u'Run','PLSRDGXudTSm81lledAXOlUg_AGGPu8Unz','Morning','','','',''],
                29:[u'Ηλιόλουστες Μέρες','PLSRDGXudTSm_AtTbW-k7r6T1cfkVzYBRz','Morning','AfterNoon','Xaroumenes','',''],
                30:[u'Να Μου Γελάς','PLSRDGXudTSm9O4-jYAvdW-sntf4zJyvxf','Morning','Xaroumenes','','','',''],
                31:[u'Coffee Break','PLSRDGXudTSm8NNRMP-Vy0N5drxdgq4D-H','Morning','','','','',''],
                32:[u'Coffee House','PLSRDGXudTSm8SwpTaGkAQ5Jg5iL6Bm9ZI','Morning','','','','',''],
                33:[u'Bedtime Stories','PLSRDGXudTSm9gXGLpMVsH9OsCAVa0aSS4','Morning','','','','',''],
                34:[u'Gloomy Sunday','PLSRDGXudTSm-NQnuXT22HM24Gep-yqTn-','Morning','','','','',''],
                35:[u'Morning Coffee Mix','PLSRDGXudTSm9N0ftZUx7SYFqmglOACOzo','Morning','','','','',''],
                36:[u'Μεσημβρινή Φωτοσύνθεση','PLSRDGXudTSm_ijRO2OTWIgYZVh-zUFLqO','Noon','Xalarwtikes','','','',''],
                37:[u'Κουρασμένα Μεσημέρια','PLSRDGXudTSm9PJfaMl2tq6I5DM--Gh8Is','Noon','Xalarwtikes','','','',''],
                38:[u'Siesta','PLSRDGXudTSm_PxZ6cpTY3jCbIwiBCDulB','Noon','','','','',''],
                39:[u'Φιλικά Γεύματα','PLSRDGXudTSm_briHS8CeFH8wOit1kF7bx','Noon','','','','',''],
                40:[u'Cooking','PLSRDGXudTSm-Wh0aT5rytRFLWx_-UUqwN','Noon','Xaroumenes','','','',''],
                41:[u'Roadtrip','PLSRDGXudTSm8HNvzKzpiKtgYuqxgBqvx8','Noon','','','','',''],
                42:[u'Παλιά Κι Αγαπημένα ','PLSRDGXudTSm8i7TXNSg8qTMjI-nJut6Qh','Noon','','','','',''],
                43:[u'Spicy Kitchen','PLSRDGXudTSm86NLFtaKp6BQN0jhNn6cSu','Noon','','','','',''],
                44:[u'Βρέχει','PLSRDGXudTSm8iujLPQKxWw9cctpjk7U0X','Noon','Xalarwtikes','','','',''],
                45:[u'Ηχογραφία','PLSRDGXudTSm9YeqdHsDGyBMKIL2Z0OuQ6','Noon','','','','',''],
                46:[u'Feel Free','PLSRDGXudTSm9ef9QK9RHoEoF0LYDekDqD','Noon','','','','',''],
                47:[u'Motel','PLSRDGXudTSm_P3C100vwpUoDrFSIoHd4W','Noon','','','','',''],
                48:[u' Rock And Roll Can Never Die','PLSRDGXudTSm91sTOCqvcriskEOeWYQR55','Noon','','','','',''],
                49:[u'Time For Change','PLSRDGXudTSm-KuNKUvprN6UC9B1igpjqp','Noon','Xalarwtikes','','','',''],
                50:[u'Ζαλισμένα Βλέμματα','PLSRDGXudTSm-pQikhv7GmvfnKMniKYRTN','Noon','Xalarwtikes','','','',''],
                51:[u'Wasted Hours','PLSRDGXudTSm9IMH2AGUcHxibhR4q99pKT','Noon','Xalarwtikes','','','',''],
                52:[u'Cover Me','PLSRDGXudTSm-ByLvhpbeKHaP0wBdT0HTN','Noon','','','','',''],
                53:[u'Lost Soul','PLSRDGXudTSm9TLK26n-FF6MXU5XzTCvpY','Noon','','','','',''],
                54:[u'Book & Jazz Lovers','PLSRDGXudTSm9O99uACdAnV45fy4ecayMk','Noon','','','','',''],
                55:[u'Βροχερές Πόλεις','PLSRDGXudTSm--MPtv6W78kv-CtUcSfz_W','Noon','Xalarwtikes','','','',''],
                56:[u'Ταξίδια Του Νου','PLSRDGXudTSm_bcclai3wifLRwUZ7Ktwz1','Noon','','','','',''],
                57:[u'Γειτονιές Του Kόσμου','PLSRDGXudTSm8kCNG360eMTCDfKNjLpQxl','Noon','','','','',''],
                58:[u'Χαλαρά Απογεύματα','PLSRDGXudTSm9Xj6L-VtrNkCQCB_hiSCCu','AfterNoon','Xalarwtikes','','','',''],
                59:[u'Ηλιοβασιλέματα ','PLSRDGXudTSm-dqLUnizlthJoTZv4zxpG0','AfterNoon','','','','',''],
                60:[u'Γκρούβι Δειλινά','PLSRDGXudTSm-hjZ8u8aK3hP3Sl-QlaUvm','AfterNoon','Xaroumenes','','','',''],
                61:[u'Cozy Afternoon','','AfterNoon','Xalarwtikes','','','',''],
                62:[u'Cold Sun','PLSRDGXudTSm_pSYlv34tKaUQMtJ938A9H','AfterNoon','Xalarwtikes','','','',''],
                63:[u'Sunset Colours','PLSRDGXudTSm-4fcZsSrF-H7xsQSpAKsde','AfterNoon','Xalarwtikes','','','',''],
                65:[u'Ήρεμο Σούρουπο','PLSRDGXudTSm_1naoBlLeboWzPhBWleelz','AfterNoon','Xalarwtikes','','','',''],
                66:[u'Early Drinks','PLSRDGXudTSm_rUR_oixYeNjWuFPAIGh-c','AfterNoon','','','','',''],
                67:[u'Καφές Και Τσιγάρα','PLSRDGXudTSm9VMAY76QRyvE4fKSg6KIng','AfterNoon','Xalarwtikes','','','',''],
                68:[u'Evening Thoughts','PLSRDGXudTSm-YJGOGJ-DxGR2ofKsCeAgJ','AfterNoon','','','','',''],
                69:[u'Ανοιχτά Παράθυρα','PLSRDGXudTSm9RBbuRuecRT4gkljs00NvZ','AfterNoon','','','','',''],
                70:[u'Beautiful Girls','PLSRDGXudTSm-wdE3ylaTQNKU0B2LGjb1F','AfterNoon','','','','',''],
                71:[u'Urban Streets','PLSRDGXudTSm_-hppqz7GgnFRTekE6iPpZ','AfterNoon','','','','',''],
                72:[u'Take Me Out Tonight','PLSRDGXudTSm8_PQVJeo-eT2h0BynHwI9l','AfterNoon','Xaroumenes','','','',''],
                73:[u'Sun Is Shining','PLSRDGXudTSm86oU9qJqMqsjrf913H6Enh','AfterNoon','Xaroumenes','','','',''],
                74:[u'Αστική Ραστώνη','PLSRDGXudTSm-mp6IoYzzF4ay7B6-3RoTt','AfterNoon','Xalarwtikes','','','',''],
                75:[u'Beach Bar','PLSRDGXudTSm-HGfTUJ0Kv5oTAx2CJ1rHL','AfterNoon','Xalarwtikes','','','',''],
                76:[u'Μυρωδιά Καλοκαιριού','PLSRDGXudTSm-biunSvYkknQ2Zo8sy-ksy','AfterNoon','Xaroumenes','','','',''],
                77:[u'Berlin','PLSRDGXudTSm9Xa90FTnGl1hT5cM8PjoDg','AfterNoon','','','','',''],
                78:[u'Αλητεία','PLSRDGXudTSm8Oze0XBFxiuLnZLlH13gBN','AfterNoon','','','','',''],
                79:[u'Summer Breeze','PLSRDGXudTSm8UxbqRlMADkOXvOtmJAn5I','AfterNoon','','','','',''],
                80:[u'Θερινά Μπαλκόνια','PLSRDGXudTSm8AaE8Z5m-OIkV9gOCxnbRT','AfterNoon','Xaroumenes','','','',''],
                81:[u'Τεκίλα Και Ξαπλώστρα','PLSRDGXudTSm8P-oaR0zD3ruym9GsCxB5c','AfterNoon','Xaroumenes','','','',''],
                82:[u'Running To The Sea','PLSRDGXudTSm8ol9XFvEjDHaKfrerYnRaM','AfterNoon','','','','',''],
                83:[u'Storm Is Coming','PLSRDGXudTSm-KJ9U_7J2Cih1YKqlR9kL4','AfterNoon','','','','',''],
                84:[u'Drum And Break','PLSRDGXudTSm96qYLqZ64JR7Rb_SZnt0GK','AfterNoon','','','','',''],
                85:[u'Lazy Nights','PLSRDGXudTSm8Redbxk-LD0HhYPXfA2jR0','Night','Xalarwtikes','','','',''],
                86:[u'Nightcall','PLSRDGXudTSm8TsiG2i5h0fEOk2cGlhErq','Night','','','','',''],
                87:[u'Νανουρίσματα','PLSRDGXudTSm_UCTY9O7dwXcnUJjomfw4P','Night','','','','',''],
                88:[u'Midnight Soundtrack','PLSRDGXudTSm_i9wWj_flBFOA4LrHmv95L','Night','','','','',''],
                89:[u'Night Drive','PLSRDGXudTSm8YHBSLO74Pt8mVziJPgG1g','Night','','','','',''],
                90:[u'Night Focus','PLSRDGXudTSm9vBPEPUa9pmhVF-3tQtd9j','Night','','','','',''],
                91:[u'On My Mind Tonight','PLSRDGXudTSm-xWSdhNpdiArMEyFHY5W8J','Night','','','','',''],
                92:[u'Another Sleepless Night','PLSRDGXudTSm8VaFEDNOkxWGHHMO7vswtu','Night','','','','',''],
                93:[u'Be Mine Tonight','PLSRDGXudTSm-B1h2e77lYd5rFWjDMgkkW','Night','','','','',''],
                94:[u'Night Flight','PLSRDGXudTSm_JkwSU4XXudxE8d3qvJd05','Night','','','','',''],
                95:[u'Αγκαλιές Και Ξενύχτια','PLSRDGXudTSm8d61f0Kxt7gS0IEBy_X4JT','Night','Xalarwtikes','','','',''],
                96:[u'Night Confessions','PLSRDGXudTSm_nm79qLxvFv9Z2aJAXwNG8','Night','','','','',''],
                97:[u'Between The Bars','PLSRDGXudTSm8vYtC7HSPv9s75_f1ADz74','Night','','','','',''],
                98:[u'Αστρικά Ταξίδια','PLSRDGXudTSm-7UHa7DySI1F1DPCIC7P8Z','Night','','','','',''],
                99:[u'Sex','PLSRDGXudTSm9XSd25m9BxiHjWvktIwMyf','Night','','','','',''],
                100:[u'Darkness','PLSRDGXudTSm8vfDWxlAleskd0H7LFZ6Pb','Night','','','','',''],
                101:[u'Hangover','PLSRDGXudTSm-v-Bo3nXm-Nc3ynsU8CD51','Night','','','','',''],
                102:[u'Ζεστές Νύχτες , Δροσερά Ποτά','PLSRDGXudTSm_p0epavyFy9fER7zKI8PIg','Night','','','','',''],
                103:[u'It\'s Late','PLSRDGXudTSm9CoKUGvCjqLi-l-Jvi3QtT','Night','','','','',''],
                104:[u'Insomnia','PLSRDGXudTSm-tL-j06tLIMmkhE8UsJsXE','Night','','','','',''],
                105:[u'Under The Same Sky','PLSRDGXudTSm85fbGHbXRy4bEfpryGW3Fw','Night','','','','',''],
                106:[u'Σκοτοδίνη','PLSRDGXudTSm8ZM9h8wE7PBF5kmXK4cBWd','Night','','','','',''],
                107:[u'One Last Cigarette','PLSRDGXudTSm9otHZtrvGbz1oVGNaEgbZv','Night','','','','',''],
                108:[u'A Glass Away ','PLSRDGXudTSm9K2iL1nS6pYRR_ofNLoSnX','Xaroumenes','','','','',''],
                109:[u'Lose Yourself to Dance','PLSRDGXudTSm98jiEDIZ6BJskt5TgpM1L1','Xaroumenes','','','','',''],
                110:[u'Positive Vibes','PLSRDGXudTSm8ZX_aQd2Y9gBeKOZFgOyDW','Xaroumenes','','','','',''],
                111:[u'Τραγούδια Στην Μπανιέρα','PLSRDGXudTSm99iBZTdQOU1K0PEsQs_0D7','Xaroumenes','','','','',''],
                112:[u'Κορμιά Ηλιοκαμένα','PLSRDGXudTSm8mpQq6_vP_T-8ujNK8cusK','Xaroumenes','','','','',''],
                113:[u'Jump Jive And Wail','PLSRDGXudTSm_nPFigFzMcBGnsq1RDGm9o','Xaroumenes','','','','',''],
                114:[u'Cocktail Hour','PLSRDGXudTSm-WKd-wbhT9MmmMADSTXl4-','Xaroumenes','','','','',''],
                115:[u'Τροπικές Παραλίες','PLSRDGXudTSm8vnOwN8EfLrlqv4nNkB9Cr','Xaroumenes','','','','',''],
                116:[u'Ρούμι Και Ρούμπα','PLSRDGXudTSm8k2MMHJioAn01GVenAKTOF','Xaroumenes','','','','',''],
                117:[u'Twist \'n\' Roll','PLSRDGXudTSm_zeSIV1f3hj8ZJXqu1cQjP','Xaroumenes','','','','',''],
                118:[u'Don\'t Worry','PLSRDGXudTSm9l4QUVfQBW-s_3q8c2nkZk','Xaroumenes','','','','',''],
                119:[u'Εξωτική Ομορφιά','PLSRDGXudTSm9hzn4xBIQoJNsnByn5GPFu','Xaroumenes','','','','',''],
                120:[u'Mess Up','PLSRDGXudTSm8heOY3qkZPyaScd3mOBTM8','Xaroumenes','','','','',''],
                121:[u'Old School Tunes','PLSRDGXudTSm8GErRpPV-Am5p9Ly2ZJxiN','Xaroumenes','','','','',''],
                122:[u'Get High','PLSRDGXudTSm86xvQEywhgEUp6ld5CdCdH','Xalarwtikes','','','','',''],
                123:[u'Underground','PLSRDGXudTSm_JxNRWQ4hdsSJSlxVbzr2d','Xalarwtikes','','','','',''],
                124:[u'Ατέλειωτα Καλοκαίρια','PLSRDGXudTSm-CxojOlMyZU3xcF5T8VIX9','Xalarwtikes','','','','',''],
                125:[u'Έρημες Ακρογιαλιές','PLSRDGXudTSm-j3G2qLXqtHXh0jEmnHzu1','Xalarwtikes','','','','',''],
                126:[u'Friday Dreams','PLSRDGXudTSm9RYA1iNuEaYymnPem9rUTg','Xalarwtikes','','','','',''],
                127:[u'Vitamin Sea','PLSRDGXudTSm_LfewE-ZetFswJw-gAPmdV','Xalarwtikes','','','','',''],
                # 128:[u'','','','','','','',''],
                # 129:[u'','','','','','','',''],
                # 130:[u'','','','','','','',''],
                # 131:[u'','','','','','','',''],
                # 132:[u'','','','','','','',''],
                # 133:[u'','','','','','','',''],
                # 134:[u'','','','','','','',''],
                # 135:[u'','','','','','','',''],
                # 136:[u'','','','','','','',''],
                # 137:[u'','','','','','','',''],
                # 138:[u'','','','','','','',''],
                # 139:[u'','','','','','','',''],
                # 140:[u'','','','','','','',''],
                # 141:[u'','','','','','','','']





            }
