# -*- coding: utf-8 -*-
#   ===================================
#       kasetophon sto termatiko
#   ===================================
#               AllPlaylists
#   ===================================
__author__ = "Simakis Panagiotis"
__license__ = "GPL"
__email__ = "sp1thas@autistici.org"
#   ===================================
# \b&v.*'\b
def GetThem(category):
    allPlaylists =  {
                1:[u'Bob Marley','PLSRDGXudTSm_x9lRMuGbm6Mf-Gx8NfmfW','Reggae','','','','','','','','','','','',''],
                2:[u'Summer Roots', 'PLSRDGXudTSm8YFJzLVX8Yk0ZcwxVdooai','Reggae','','','','','','','','','','','',''],
                3:[u'Mad About You','PLSRDGXudTSm8x2vcosYPD1sqE3cnFVw8c','HipTripHop','Tuesday','','','','','','','','','','','',''],
                4:[u'Ηλεκτρικά Ξημερώματα', 'PLSRDGXudTSm9JVxz0KRPIKocBePENGI7M','Reading','Morning','Electro','Orchestral','Friday','','','','','','','',''],
                5:[u'Κεφάτα Πρωινά', 'PLSRDGXudTSm-T0SH2WcZ2lVxB6H1RVGnn', 'Popular','Morning','Xaroumenes','FoodLovers','Monday','','','','','','','','',''],
                6:[u'Smoky Head','PLSRDGXudTSm8A9sBOvMcmCbG6VIUt2-Es', 'Rock','AlcoholLovers','','','','','','','','','','','','',''],
                7:[u'Feeling Good','PLSRDGXudTSm-VAX1PRgL7cTgmcRnxt6Mq', 'Xaroumenes','Morning','Friday','','','','','','','','','','',''],
                8:[u'Πρωινό Στο Κρεβάτι','PLSRDGXudTSm9edl7Bha5Py6t0eM62kj8l','Morning','Xalarwtikes','FoodLovers','BedLovers','Sunday','','','','','','',''],
                9:[u'Make My Day','PLSRDGXudTSm9duWeggg_scs8XdnTmN_kE','Morning','Xaroumenes','Electro','Thursday','','','','','','','',''],
                10:[u'Good Morning Sunshine ','PLSRDGXudTSm-jkPYsnTWugKfNSatNc8C_','Morning','BedLovers','SunLovers','Saturday','','','','','','','',''],
                11:[u'Sunday Morning','PLSRDGXudTSm-Wj0T3QRbvvZpIVmyBW9gn','Morning','Xalarwtikes','BedLovers','Sunday','','','','','','','',''],
                12:[u'Γυμναστική','PLSRDGXudTSm8xskH84A8HmuqTo-ddGVwX','Morning','Xaroumenes','Electro','Activity','Monday','','','','','','',''],
                13:[u'Mellow Morning','PLSRDGXudTSm_55t0DWCrcVNxX2AJDkm_f','Morning','Remixes','Acoustic','Sunday','','','','','','','',''],
                14:[u'Αγουροξυπνήματα','PLSRDGXudTSm8rOJ1ecbS1fdomXbNxdkI5','Morning','Xaroumenes','Tuesday','','','','','','','','',''],
                15:[u'Καφές και βιβλία','PLSRDGXudTSm8gle58o1uoCgV3f1GPs0Iy','Morning','World','Acoustic','CoffeeLovers','BookLovers','BedLovers','Saturday','','','','','','',''],
                16:[u'Morning Energy','PLSRDGXudTSm9hkkfPPC-NRiZh62VFMyOB','Morning','Rock','Wednesday','','','','','','','','',''],
                17:[u'Coffee Time','PLSRDGXudTSm_dpRujR-T0I5OqLBHEuNem','Morning','XalarwtikesΦ','CoffeeLovers','Activity','Tuesday','','','','','','',''],
                18:[u'Brunch','PLSRDGXudTSm9JIAf6KEkDsuPeeMxEwMi9','Morning','FoodLovers','Activity','Sunday','','','','','','','',''],
                19:[u'Μουσικές του Κόσμου','PLSRDGXudTSm9gBoLbXztA5M6a5qM3oyav','Morning','Xaroumenes','World','Monday','','','','','','','',''],
                20:[u'Λούνα Πάρκ','PLSRDGXudTSm-z5IlB1QE7kvR1m7kVlVI-','Morning','World','Orchestral','Sunday','','','','','','','',''],
                21:[u'Cleaning','PLSRDGXudTSm_qMSnxgy8fZMVA1RVu5Q8Z','Morning','Xaroumenes','Activity','Wednesday','','','','','','','',''],
                22:[u'Home','PLSRDGXudTSm8N7b-RzOHzYRsHl8DKzDbS','Morning','Noon','AlternativeIndie','Acoustic','BedLovers','Sunday','','','','','','',''],
                23:[u'Τα Ραδιοφωνικά','PLSRDGXudTSm_jSzrYHL_aW_TL-sdJAzSP','Morning','Thursday','','','','','','','','','',''],
                24:[u'Τα Τζαζεμένα','PLSRDGXudTSm8nRhAaeO0Ichb6mvlMiS8V','Morning','Xalarwtikes','Jazz','Remixes','Thursday','','','','','','',''],
                25:[u'Working Fridays','PLSRDGXudTSm8qW3nlYA_QO6Fv4nKrGpza','Morning','Remixes','Activity','Friday','','','','','','','',''],
                26:[u'Jazz And Coffee','PLSRDGXudTSm9EDBMEFBXUXRaAA-TeGmgq','Morning','Jazz','Vintage','CoffeeLovers','Monday','','','','','','',''],
                27:[u'Blue Monday','PLSRDGXudTSm9EcBaBk0fk1oCqwb8gsLde','Morning','Xalarwtikes','Monday','','','','','','','','',''],
                28:[u'Run','PLSRDGXudTSm81lledAXOlUg_AGGPu8Unz','Morning','Electro','TravelLovers','Activity','','','','','','','',''],
                29:[u'Ηλιόλουστες Μέρες','PLSRDGXudTSm_AtTbW-k7r6T1cfkVzYBRz','Morning','AfterNoon','Xaroumenes','SunLovers','Thursday','','','','','','',''],
                30:[u'Να Μου Γελάς','PLSRDGXudTSm9O4-jYAvdW-sntf4zJyvxf','Morning','Xaroumenes','Acoustic','Friday','','','','','','','','',''],
                31:[u'Coffee Break','PLSRDGXudTSm8NNRMP-Vy0N5drxdgq4D-H','Morning','CoffeeLovers','Wednesday','','','','','','','','','',''],
                32:[u'Coffee House','PLSRDGXudTSm8SwpTaGkAQ5Jg5iL6Bm9ZI','Morning','Electro','Thursday','','','','','','','','','',''],
                33:[u'Bedtime Stories','PLSRDGXudTSm9gXGLpMVsH9OsCAVa0aSS4','Morning','BedLovers','Sunday','','','','','','','','','',''],
                34:[u'Gloomy Sunday','PLSRDGXudTSm-NQnuXT22HM24Gep-yqTn-','Morning','AlternativeIndie','Acoustic','BedLovers','Sunday','','','','','','','',''],
                35:[u'Morning Coffee Mix','PLSRDGXudTSm9N0ftZUx7SYFqmglOACOzo','Morning','Electro','Remixes','CoffeeLovers','BedLovers','Friday','','','','','','',''],
                36:[u'Μεσημβρινή Φωτοσύνθεση','PLSRDGXudTSm_ijRO2OTWIgYZVh-zUFLqO','Noon','Xalarwtikes','World','SunLovers','','','','','','','','',''],
                37:[u'Κουρασμένα Μεσημέρια','PLSRDGXudTSm9PJfaMl2tq6I5DM--Gh8Is','Noon','Xalarwtikes','AlternativeIndie','Acoustic','BedLovers','Tuesday','','','','','','',''],
                38:[u'Siesta','PLSRDGXudTSm_PxZ6cpTY3jCbIwiBCDulB','Noon','Electro','BedLovers','Activity','Tuesday','','','','','','','',''],
                39:[u'Φιλικά Γεύματα','PLSRDGXudTSm_briHS8CeFH8wOit1kF7bx','Noon','FoodLovers','Activity','Saturday','','','','','','','','',''],
                40:[u'Cooking','PLSRDGXudTSm-Wh0aT5rytRFLWx_-UUqwN','Noon','Xaroumenes','FoodLovers','Activity','Tuesday','','','','','','','',''],
                41:[u'Roadtrip','PLSRDGXudTSm8HNvzKzpiKtgYuqxgBqvx8','Noon','Rock','TravelLovers','Saturday','','','','','','','','',''],
                42:[u'Παλιά Κι Αγαπημένα ','PLSRDGXudTSm8i7TXNSg8qTMjI-nJut6Qh','Noon','Vintage','Wednesday','','','','','','','','','',''],
                43:[u'Spicy Kitchen','PLSRDGXudTSm86NLFtaKp6BQN0jhNn6cSu','Noon','World','FoodLovers','','','','','','','','','',''],
                44:[u'Βρέχει','PLSRDGXudTSm8iujLPQKxWw9cctpjk7U0X','Noon','Xalarwtikes','RainLovers','Wednesday','','','','','','','','',''],
                45:[u'Ηχογραφία','PLSRDGXudTSm9YeqdHsDGyBMKIL2Z0OuQ6','Noon','World','Orchestral','Acoustic','TravelLovers','Tuesday','','','','','','',''],
                46:[u'Feel Free','PLSRDGXudTSm9ef9QK9RHoEoF0LYDekDqD','Noon','AlternativeIndie','Acoustic','TravelLovers','Sunday','','','','','','','',''],
                47:[u'Motel','PLSRDGXudTSm_P3C100vwpUoDrFSIoHd4W','Noon','Rock','Acoustic','TravelLovers','Sunday','','','','','','','',''],
                48:[u' Rock And Roll Can Never Die','PLSRDGXudTSm91sTOCqvcriskEOeWYQR55','Noon','Rock','Vintage','Tuesday','','','','','','','','',''],
                49:[u'Time For Change','PLSRDGXudTSm-KuNKUvprN6UC9B1igpjqp','Noon','Xalarwtikes','Remixes','Acoustic','Monday','Melagxolikes','','','','','','',''],
                50:[u'Ζαλισμένα Βλέμματα','PLSRDGXudTSm-pQikhv7GmvfnKMniKYRTN','Noon','Xalarwtikes','AlcoholLovers','Sunday','','','','','','','','',''],
                51:[u'Wasted Hours','PLSRDGXudTSm9IMH2AGUcHxibhR4q99pKT','Noon','Xalarwtikes','Wednesday','','','','','','','','','',''],
                52:[u'Cover Me','PLSRDGXudTSm-ByLvhpbeKHaP0wBdT0HTN','Noon','Remixes','Orchestral','Sunday','','','','','','','','',''],
                53:[u'Lost Soul','PLSRDGXudTSm9TLK26n-FF6MXU5XzTCvpY','Noon','Vintage','Saturday','','','','','','','','','',''],
                54:[u'Book & Jazz Lovers','PLSRDGXudTSm9O99uACdAnV45fy4ecayMk','Noon','BookLovers','','','','','','','','','','',''],
                55:[u'Βροχερές Πόλεις','PLSRDGXudTSm--MPtv6W78kv-CtUcSfz_W','Noon','Xalarwtikes','RainLovers','Tuesday','','','','','','','','',''],
                56:[u'Ταξίδια Του Νου','PLSRDGXudTSm_bcclai3wifLRwUZ7Ktwz1','Noon','Jazz','Orchestral','TravelLovers','','','','','','','','',''],
                57:[u'Γειτονιές Του Kόσμου','PLSRDGXudTSm8kCNG360eMTCDfKNjLpQxl','Noon','World','','','','','','','','','','',''],
                58:[u'Χαλαρά Απογεύματα','PLSRDGXudTSm9Xj6L-VtrNkCQCB_hiSCCu','AfterNoon','Xalarwtikes','Thursday','','','','','','','','','',''],
                59:[u'Ηλιοβασιλέματα ','PLSRDGXudTSm-dqLUnizlthJoTZv4zxpG0','AfterNoon','Electro','SunLovers','Thursday','','','','','','','','',''],
                60:[u'Γκρούβι Δειλινά','PLSRDGXudTSm-hjZ8u8aK3hP3Sl-QlaUvm','AfterNoon','Xaroumenes','Friday','','','','','','','','','',''],
                61:[u'Cozy Afternoon','','AfterNoon','Xalarwtikes','Wednesday','','','','','','','','','',''],
                62:[u'Cold Sun','PLSRDGXudTSm_pSYlv34tKaUQMtJ938A9H','AfterNoon','Xalarwtikes','Electro','SunLovers','','','','','','','','',''],
                63:[u'Sunset Colours','PLSRDGXudTSm-4fcZsSrF-H7xsQSpAKsde','AfterNoon','Xalarwtikes','Acoustic','SunLovers','','','','','','','','',''],
                65:[u'Ήρεμο Σούρουπο','PLSRDGXudTSm_1naoBlLeboWzPhBWleelz','AfterNoon','Xalarwtikes','SeaLovers','','','','','','','','','',''],
                66:[u'Early Drinks','PLSRDGXudTSm_rUR_oixYeNjWuFPAIGh-c','AfterNoon','AlcoholLovers','Activity','Friday','','','','','','','','',''],
                67:[u'Καφές Και Τσιγάρα','PLSRDGXudTSm9VMAY76QRyvE4fKSg6KIng','AfterNoon','Xalarwtikes','AlternativeIndie','CoffeeLovers','','','','','','','','',''],
                68:[u'Evening Thoughts','PLSRDGXudTSm-YJGOGJ-DxGR2ofKsCeAgJ','AfterNoon','AlternativeIndie','Acoustic','Tuesday','','','','','','','','',''],
                69:[u'Ανοιχτά Παράθυρα','PLSRDGXudTSm9RBbuRuecRT4gkljs00NvZ','AfterNoon','Vintage','','','','','','','','','','',''],
                70:[u'Beautiful Girls','PLSRDGXudTSm-wdE3ylaTQNKU0B2LGjb1F','AfterNoon','AlternativeIndie','Friday','','','','','','','','','',''],
                71:[u'Urban Streets','PLSRDGXudTSm_-hppqz7GgnFRTekE6iPpZ','AfterNoon','TravelLovers','Tuesday','','','','','','','','','',''],
                72:[u'Take Me Out Tonight','PLSRDGXudTSm8_PQVJeo-eT2h0BynHwI9l','AfterNoon','Xaroumenes','Activity','Friday','','','','','','','','',''],
                73:[u'Sun Is Shining','PLSRDGXudTSm86oU9qJqMqsjrf913H6Enh','AfterNoon','Xaroumenes','World','SunLovers','','','','','','','','',''],
                74:[u'Αστική Ραστώνη','PLSRDGXudTSm-mp6IoYzzF4ay7B6-3RoTt','AfterNoon','Xalarwtikes','SunLovers','Sunday','','','','','','','','',''],
                75:[u'Beach Bar','PLSRDGXudTSm-HGfTUJ0Kv5oTAx2CJ1rHL','AfterNoon','Xalarwtikes','SeaLovers','','','','','','','','','',''],
                76:[u'Μυρωδιά Καλοκαιριού','PLSRDGXudTSm-biunSvYkknQ2Zo8sy-ksy','AfterNoon','Xaroumenes','Electro','SeaLovers','','','','','','','','',''],
                77:[u'Berlin','PLSRDGXudTSm9Xa90FTnGl1hT5cM8PjoDg','AfterNoon','Electro','TravelLovers','Friday','','','','','','','','',''],
                78:[u'Αλητεία','PLSRDGXudTSm8Oze0XBFxiuLnZLlH13gBN','AfterNoon','Rock','TravelLovers','Friday','','','','','','','','',''],
                79:[u'Summer Breeze','PLSRDGXudTSm8UxbqRlMADkOXvOtmJAn5I','AfterNoon','Electro','SeaLovers','','','','','','','','','',''],
                80:[u'Θερινά Μπαλκόνια','PLSRDGXudTSm8AaE8Z5m-OIkV9gOCxnbRT','AfterNoon','Xaroumenes','World','Monday','','','','','','','','',''],
                81:[u'Τεκίλα Και Ξαπλώστρα','PLSRDGXudTSm8P-oaR0zD3ruym9GsCxB5c','AfterNoon','Xaroumenes','Remixes','AlcoholLovers','SunLovers','','','','','','','',''],
                82:[u'Running To The Sea','PLSRDGXudTSm8ol9XFvEjDHaKfrerYnRaM','AfterNoon','Electro','SeaLovers','','','','','','','','','',''],
                83:[u'Storm Is Coming','PLSRDGXudTSm-KJ9U_7J2Cih1YKqlR9kL4','AfterNoon','AlternativeIndie','RainLovers','Melagxolikes','','','','','','','','',''],
                84:[u'Drum And Break','PLSRDGXudTSm96qYLqZ64JR7Rb_SZnt0GK','AfterNoon','Remixes','','','','','','','','','','',''],
                85:[u'Lazy Nights','PLSRDGXudTSm8Redbxk-LD0HhYPXfA2jR0','Night','Xalarwtikes','AlternativeIndie','Activity','Thursday','','','','','','','',''],
                86:[u'Nightcall','PLSRDGXudTSm8TsiG2i5h0fEOk2cGlhErq','Night','Electro','Activity','Thursday','','','','','','','','',''],
                87:[u'Νανουρίσματα','PLSRDGXudTSm_UCTY9O7dwXcnUJjomfw4P','Night','Orchestral','BedLovers','Activity','Sunday','','','','','','','',''],
                88:[u'Midnight Soundtrack','PLSRDGXudTSm_i9wWj_flBFOA4LrHmv95L','Night','AlternativeIndie','Wednesday','Melagxolikes','','','','','','','','',''],
                89:[u'Night Drive','PLSRDGXudTSm8YHBSLO74Pt8mVziJPgG1g','Night','AlternativeIndie','TravelLovers','Tuesday','','','','','','','','',''],
                90:[u'Night Focus','PLSRDGXudTSm9vBPEPUa9pmhVF-3tQtd9j','Night','Orchestral','BookLovers','','','','','','','','','',''],
                91:[u'On My Mind Tonight','PLSRDGXudTSm-xWSdhNpdiArMEyFHY5W8J','Night','Jazz','','','','','','','','','','',''],
                92:[u'Another Sleepless Night','PLSRDGXudTSm8VaFEDNOkxWGHHMO7vswtu','Night','Vintage','BedLovers','','','','','','','','','',''],
                93:[u'Be Mine Tonight','PLSRDGXudTSm-B1h2e77lYd5rFWjDMgkkW','Night','Electro','Friday','','','','','','','','','',''],
                94:[u'Night Flight','PLSRDGXudTSm_JkwSU4XXudxE8d3qvJd05','Night','Electro','TravelLovers','','','','','','','','','',''],
                95:[u'Αγκαλιές Και Ξενύχτια','PLSRDGXudTSm8d61f0Kxt7gS0IEBy_X4JT','Night','Xalarwtikes','AlternativeIndie','BedLovers','','','','','','','','',''],
                96:[u'Night Confessions','PLSRDGXudTSm_nm79qLxvFv9Z2aJAXwNG8','Night','AlternativeIndie','BedLovers','','','','','','','','','',''],
                97:[u'Between The Bars','PLSRDGXudTSm8vYtC7HSPv9s75_f1ADz74','Night','AlternativeIndie','AlcoholLovers','Activity','Saturday','Melagxolikes','','','','','','',''],
                98:[u'Αστρικά Ταξίδια','PLSRDGXudTSm-7UHa7DySI1F1DPCIC7P8Z','Night','Orchestral','BedLovers','TravelLovers','Tuesday','Melagxolikes','','','','','','',''],
                99:[u'Sex','PLSRDGXudTSm9XSd25m9BxiHjWvktIwMyf','Night','BedLovers','Activity','Thursday','','','','','','','','',''],
                100:[u'Darkness','PLSRDGXudTSm8vfDWxlAleskd0H7LFZ6Pb','Night','Wednesday','Melagxolikes','','','','','','','','','',''],
                101:[u'Hangover','PLSRDGXudTSm-v-Bo3nXm-Nc3ynsU8CD51','Night','Electro','AlternativeIndie','AlcoholLovers','BedLovers','Saturday','','','','','','',''],
                102:[u'Ζεστές Νύχτες , Δροσερά Ποτά','PLSRDGXudTSm_p0epavyFy9fER7zKI8PIg','Night','Electro','AlcoholLovers','','','','','','','','','',''],
                103:[u'It\'s Late','PLSRDGXudTSm9CoKUGvCjqLi-l-Jvi3QtT','Night','Electro','Sunday','','','','','','','','','',''],
                104:[u'Insomnia','PLSRDGXudTSm-tL-j06tLIMmkhE8UsJsXE','Night','AlternativeIndie','Acoustic','BedLovers','Activity','','','','','','','',''],
                105:[u'Under The Same Sky','PLSRDGXudTSm85fbGHbXRy4bEfpryGW3Fw','Night','Rock','Orchestral','Melagxolikes','','','','','','','','',''],
                106:[u'Σκοτοδίνη','PLSRDGXudTSm8ZM9h8wE7PBF5kmXK4cBWd','Night','Melagxolikes','','','','','','','','','','',''],
                107:[u'One Last Cigarette','PLSRDGXudTSm9otHZtrvGbz1oVGNaEgbZv','Night','AlternativeIndie','AlcoholLovers','Melagxolikes','','','','','','','','',''],
                108:[u'A Glass Away ','PLSRDGXudTSm9K2iL1nS6pYRR_ofNLoSnX','Xaroumenes','AlcoholLovers','Saturday','','','','','','','','','',''],
                109:[u'Lose Yourself to Dance','PLSRDGXudTSm98jiEDIZ6BJskt5TgpM1L1','Xaroumenes','Friday','','','','','','','','','','',''],
                110:[u'Positive Vibes','PLSRDGXudTSm8ZX_aQd2Y9gBeKOZFgOyDW','Xaroumenes','','','','','','','','','','','',''],
                111:[u'Τραγούδια Στην Μπανιέρα','PLSRDGXudTSm99iBZTdQOU1K0PEsQs_0D7','Xaroumenes','Activity','','','','','','','','','','',''],
                112:[u'Κορμιά Ηλιοκαμένα','PLSRDGXudTSm8mpQq6_vP_T-8ujNK8cusK','Xaroumenes','SunLovers','','','','','','','','','','',''],
                113:[u'Jump Jive And Wail','PLSRDGXudTSm_nPFigFzMcBGnsq1RDGm9o','Xaroumenes','Vintage','Saturday','','','','','','','','','',''],
                114:[u'Cocktail Hour','PLSRDGXudTSm-WKd-wbhT9MmmMADSTXl4-','Xaroumenes','Vintage','AlcoholLovers','Activity','Saturday','','','','','','','',''],
                115:[u'Τροπικές Παραλίες','PLSRDGXudTSm8vnOwN8EfLrlqv4nNkB9Cr','Xaroumenes','SeaLovers','Monday','','','','','','','','','',''],
                116:[u'Ρούμι Και Ρούμπα','PLSRDGXudTSm8k2MMHJioAn01GVenAKTOF','Xaroumenes','World','AlcoholLovers','Saturday','','','','','','','','',''],
                117:[u'Twist \'n\' Roll','PLSRDGXudTSm_zeSIV1f3hj8ZJXqu1cQjP','Xaroumenes','Rock','Vintage','Friday','','','','','','','','',''],
                118:[u'Don\'t Worry','PLSRDGXudTSm9l4QUVfQBW-s_3q8c2nkZk','Xaroumenes','Monday','','','','','','','','','','',''],
                119:[u'Εξωτική Ομορφιά','PLSRDGXudTSm9hzn4xBIQoJNsnByn5GPFu','Xaroumenes','World','','','','','','','','','','',''],
                120:[u'Mess Up','PLSRDGXudTSm8heOY3qkZPyaScd3mOBTM8','Xaroumenes','Remixes','','','','','','','','','','',''],
                121:[u'Old School Tunes','PLSRDGXudTSm8GErRpPV-Am5p9Ly2ZJxiN','Xaroumenes','Vintage','','','','','','','','','','',''],
                122:[u'Get High','PLSRDGXudTSm86xvQEywhgEUp6ld5CdCdH','Xalarwtikes','AlcoholLovers','Activity','Saturday','','','','','','','','',''],
                123:[u'Underground','PLSRDGXudTSm_JxNRWQ4hdsSJSlxVbzr2d','Xalarwtikes','TravelLovers','Thursday','','','','','','','','','',''],
                124:[u'Ατέλειωτα Καλοκαίρια','PLSRDGXudTSm-CxojOlMyZU3xcF5T8VIX9','Xalarwtikes','Electro','SeaLovers','','','','','','','','','',''],
                125:[u'Έρημες Ακρογιαλιές','PLSRDGXudTSm-j3G2qLXqtHXh0jEmnHzu1','Xalarwtikes','SeaLovers','','','','','','','','','','',''],
                126:[u'Friday Dreams','PLSRDGXudTSm9RYA1iNuEaYymnPem9rUTg','Xalarwtikes','World','SeaLovers','Friday','','','','','','','','',''],
                127:[u'Vitamin Sea','PLSRDGXudTSm_LfewE-ZetFswJw-gAPmdV','Xalarwtikes','SeaLovers','','','','','','','','','','',''],
                128:[u'Where Ιs Μy Μind?','PLSRDGXudTSm_-ZCHYrptTi_CTXUzfeENA','Rock','TravelLovers','Wednesday','','','','','','','','','',''],
                129:[u'Lust For Life','PLSRDGXudTSm-YUAt7N28_t3nNZY5zcDcB','Rock','Friday','','','','','','','','','','',''],
                130:[u'Love Will Tear Us Apart','PLSRDGXudTSm8NniepmxhIs_te8OKuhlaM','Rock','Wednesday','','','','','','','','','','',''],
                131:[u'Drive','PLSRDGXudTSm-80TzVlGfmqsBO4W3uNlvt','Rock','TravelLovers','Activity','Monday','','','','','','','','',''],
                132:[u'The guns of Athens','PLSRDGXudTSm8dbZbJpBBH5EozUctc-lAl','Rock','','','','','','','','','','','',''],
                133:[u'Αρμονία Και Χάος','PLSRDGXudTSm8udgwRg3xBCTaBYq9TfxHj','Rock','','','','','','','','','','','',''],
                134:[u'Μπυρότσαρκα','PLSRDGXudTSm8SVcwep6SeLXKZoMzCNTyo','Rock','AlcoholLovers','','','','','','','','','','',''],
                135:[u'On The Road Again','PLSRDGXudTSm9VsnUtyk1IxjrLhQLmbw-E','Rock','TravelLovers','','','','','','','','','','',''],
                136:[u'Youth','PLSRDGXudTSm_Yj5wrvPu-1UCFbvxpf72R','Rock','Friday','','','','','','','','','','',''],
                137:[u'Ψυχεδέλεια','PLSRDGXudTSm-61Sbpg4-vN6rEaDUhn3Hq','Rock','AlcoholLovers','','','','','','','','','','',''],
                138:[u'Seattle Sound','PLSRDGXudTSm-zMu8FHLJqhIq-vqTr75IC','Rock','','','','','','','','','','','',''],
                139:[u'Ξεθωριασμένη Μνήμη','PLSRDGXudTSm9TD1z6XLrEqW9V1l8k_TvF','Rock','Monday','','','','','','','','','','',''],
                140:[u'Kill Me','PLSRDGXudTSm_Bn-I2vLH3Ucnfw2Sqb4ys','Rock','Wednesday','','','','','','','','','','',''],
                141:[u'Motorcycle Blues','PLSRDGXudTSm9rXz4iQLVqqnyQChFEOGi0','Rock','TravelLovers','Activity','','','','','','','','','',''],
                142:[u'British Love Guitars','PLSRDGXudTSm-JUGEUu6lfcBa75XdtYQr1','Rock','','','','','','','','','','','','','',''],
                143:[u'Άδεια Πακέτα','PLSRDGXudTSm9paqRzmW4Ny8CY2Nuouo41','Rock','Acoustic','AlcoholLovers','Melagxolikes','','','','','','','','','','',''],
                144:[u'Tarantino\'s Road Trippin\'','PLSRDGXudTSm_-SXQj1zxteRp056vrnVf1','Rock','TravelLovers','','','','','','','','','','','','',''],
                145:[u'Μοναχικές Διαδρομές','PLSRDGXudTSm9K-088EIKT2dx0F5iftvxF','Rock','TravelLovers','','','','','','','','','','','','',''],
                146:[u'Howlin\' For You','PLSRDGXudTSm9HzUc2FZ92rBt8E6bPuBnp','Rock','','','','','','','','','','','','','',''],
                147:[u'Poison','PLSRDGXudTSm8ljMPnrmFrDz4kcG9TbVmS','Rock','Melagxolikes','','','','','','','','','','','','',''],
                148:[u'Damn Girl','PLSRDGXudTSm9qCe-ra9jMiZhUe7_7ZZ79','Rock','','','','','','','','','','','','','',''],
                149:[u'Lost Game','PLSRDGXudTSm_hW1zKf8dB4KOOi_hrmleS','Rock','','','','','','','','','','','','','',''],
                150:[u'All That Jazz','PLSRDGXudTSm9YKHGhRzGzJyXt118Z52D4','Jazz','Orchestral','Tuesday','','','','','','','','','','','',''],
                151:[u'Manhattan','PLSRDGXudTSm8Rv7xtZcLu6h3VIZpEqmuo','Jazz','Vintage','Saturday','','','','','','','','','','','',''],
                152:[u'Jazzy And Sexy Nights','PLSRDGXudTSm8MZcujO7Twdfke5JSCnobg','Jazz','AlcoholLovers','Monday','','','','','','','','','','','',''],
                153:[u'Cloudy Days','PLSRDGXudTSm_M4DFkY3m3EFj4zy8dgc8g','Jazz','Vintage','Wednesday','','','','','','','','','','','',''],
                154:[u'Book & Jazz Lovers','PLSRDGXudTSm9O99uACdAnV45fy4ecayMk','Jazz','Thursday','','','','','','','','','','','','',''],
                155:[u'Cinematic Moments','PLSRDGXudTSm-ltlPolUWFU0LCIZol16qc','Jazz','Orchestral','','','','','','','','','','','','',''],
                156:[u'Θέρως','PLSRDGXudTSm-ghyCeZtqEjZHUZWGJ0m4Q','Jazz','Vintage','','','','','','','','','','','','',''],
                157:[u'Touch Me','PLSRDGXudTSm8OaFsKToNbHh4gcULDwjFI','Electro','','','','','','','','','','','','','',''],
                158:[u'Deep Universe','PLSRDGXudTSm_9bM84pQaPP976XjZBO2oJ','Electro','','','','','','','','','','','','','',''],
                159:[u'Illusions','PLSRDGXudTSm8fjOgzlwA9kOCXrx2cAVFD','Electro','','','','','','','','','','','','','',''],
                160:[u'Dive Into You','PLSRDGXudTSm9RaQB6zny3oWkc22hrZgO-','Electro','SeaLovers','','','','','','','','','','','','',''],
                161:[u'Silent Dance','PLSRDGXudTSm_m7eTe7u-SyjzcmAkZPgl-','Electro','Friday','','','','','','','','','','','','',''],
                162:[u'Electric Feel','PLSRDGXudTSm-b0zhAs2Qt5qV2WCqewm0p','Electro','AlternativeIndie','Friday','','','','','','','','','','','',''],
                163:[u'Ηλεκτρισμένα Χάδια','PLSRDGXudTSm8T-LsDQI3i0hv21ia0cAoj','Electro','','','','','','','','','','','','','',''],
                164:[u'We Own The Sky','PLSRDGXudTSm8CJExekA_shutrW1Q87IoJ','Electro','','','','','','','','','','','','','',''],
                165:[u'Sail Away','PLSRDGXudTSm8f5fNP7Oh-1Xp9nbcAD0rl','Electro','TravelLovers','SeaLovers','','','','','','','','','','','',''],
                166:[u'Run Away','PLSRDGXudTSm8EetGIKCq18tMnwmeG-jfg','AlternativeIndie','TravelLovers','Saturday','','','','','','','','','','','',''],
                167:[u'Home Alone','PLSRDGXudTSm_t4KPVHxauNBxjNLOx9fWd','AlternativeIndie','BedLovers','Activity','Saturday','','','','','','','','','','',''],
                168:[u'Me And Myself','PLSRDGXudTSm8DiJtcth7nUCNj2nsYhprq','AlternativeIndie','','','','','','','','','','','','','',''],
                169:[u'Into The Wild','PLSRDGXudTSm86N0DWOqvnjEYnhzjPwjpd','AlternativeIndie','Acoustic','BookLovers','TravelLovers','Tuesday','Melagxolikes','','','','','','','','',''],
                170:[u'Φθινόπωρο','PLSRDGXudTSm8Lnz45GgLDDWWXqcXYV9e4','AlternativeIndie','Melagxolikes','','','','','','','','','','','','',''],
                171:[u'Emptiness','PLSRDGXudTSm-0_w37uBrEA-anqYIhIRcR','AlternativeIndie','Monday','','','','','','','','','','','','',''],
                172:[u'Endless Walk','PLSRDGXudTSm-cp-sQ5QV8fv-UF39KHTx3','AlternativeIndie','TravelLovers','Activity','Thursday','','','','','','','','','','',''],
                173:[u'Let\'s Get Lost','PLSRDGXudTSm8jzlLO91E2csEBE_GYZ2uK','AlternativeIndie','Acoustic','TravelLovers','','','','','','','','','','','',''],
                174:[u'Pictures Of You','PLSRDGXudTSm8x2U5epycJZ3V2IXn3LjTT','AlternativeIndie','Melagxolikes','','','','','','','','','','','','',''],
                175:[u'Disappear','PLSRDGXudTSm9nVyhrret1O1TWTR3qMm1p','AlternativeIndie','Melagxolikes','','','','','','','','','','','','',''],
                176:[u'Beautiful Sadness','PLSRDGXudTSm-3ZcF7UX8gG_k2uRa7ZhAQ','AlternativeIndie','Melagxolikes','','','','','','','','','','','','',''],
                177:[u'Ride','PLSRDGXudTSm960vdxltgZFhN4GkC8zjiO','AlternativeIndie','TravelLovers','','','','','','','','','','','','',''],
                178:[u'Roofpop','PLSRDGXudTSm9kSb89vxEYJkwmr0ZXULcn','AlternativeIndie','','','','','','','','','','','','','',''],
                179:[u'Paris, Je T\'aime','PLSRDGXudTSm8ARZHucIzjf2roZ_v73wI0','World','Vintage','Sunday','','','','','','','','','','','',''],
                180:[u'Serenata','PLSRDGXudTSm876gyEdZez24inZB9YR1g8','World','Vintage','','','','','','','','','','','','',''],
                181:[u'Earth Blues','PLSRDGXudTSm95LUdRDvN4w_KbvBx8pv0j','World','','','','','','','','','','','','','',''],
                182:[u'Κατάστρωμα','PLSRDGXudTSm9dl38omfSkS5o6P_Gjc23g','World','TravelLovers','SeaLovers','','','','','','','','','','','',''],
                183:[u'Weekend Escape','PLSRDGXudTSm-Yj1-bhsIpm8Sr0868Gb3U','World','TravelLovers','Saturday','','','','','','','','','','','',''],
                184:[u'Γρανίτα','PLSRDGXudTSm-q56zX1wNzMKOjz6hpvHaM','World','FoodLovers','','','','','','','','','','','','',''],
                185:[u'Βαλκάνια','PLSRDGXudTSm_G3pTEY2AOi6NhbQre6vzY','World','','','','','','','','','','','','','',''],
                186:[u'Whiskey In The Jar','PLSRDGXudTSm_6mLGv0UyA7VO1DsW2FFuO','World','AlcoholLovers','','','','','','','','','','','','',''],
                187:[u'Ξενιτιά','PLSRDGXudTSm-x5YnMkbLcqL8lO3zkaQzb','World','','','','','','','','','','','','','',''],
                188:[u'Χρωματιστές Μελωδίες','PLSRDGXudTSm_QTKS1jdKyNTqq8r-AaNVR','World','Acoustic','','','','','','','','','','','','',''],
                189:[u'Φθινοπωρινό Σεργιάνι','PLSRDGXudTSm_n65dIlxA1jqCLCIsMA1Li','World','','','','','','','','','','','','','',''],
                190:[u'Γαλάζιο','PLSRDGXudTSm9021QXny6NLmvPmgoV-F9l','World','Orchestral','SeaLovers','','','','','','','','','','','',''],
                191:[u'By The Sea','PLSRDGXudTSm_qJj8BJ-mRLEMEOrAuCVt4','World','SeaLovers','','','','','','','','','','','','',''],
                192:[u'Γιασεμιά Και Ρομάντζο','PLSRDGXudTSm9xNjJRjndDkx-NSjbgSvEt','Vintage','','','','','','','','','','','','','',''],
                193:[u'Vintage Summertime','PLSRDGXudTSm9RVT5-lHYeKgxF34mKATpi','Vintage','','','','','','','','','','','','','',''],
                194:[u'Burgers And Beers','PLSRDGXudTSm_HE31rUpE9ms23g_xa2Zkg','Vintage','FoodLovers','','','','','','','','','','','','',''],
                195:[u'Vintage Wintertime','PLSRDGXudTSm_7geiWG-15W8GzwYVO52kq','Vintage','','','','','','','','','','','','','',''],
                196:[u'Flashback','PLSRDGXudTSm-umFWRRK0T7MiAt_OVWoE7','Vintage','','','','','','','','','','','','','',''],
                197:[u'When a man loves a woman','PLSRDGXudTSm8m3WuAWKq_5QCftwzvyFVI','Vintage','Monday','','','','','','','','','','','','',''],
                198:[u'Killing Me Softly','PLSRDGXudTSm-ZtwLE9BV9lGuYcTdaWMpF','Vintage','','','','','','','','','','','','','',''],
                199:[u'Dance Of Love','PLSRDGXudTSm-rRIMYv0Hs8sqCsgP578eq','Vintage','','','','','','','','','','','','','',''],
                200:[u'Πυρετός το Σαββατόβραδο','PLSRDGXudTSm-M9-UvTbg5J2c29WD-NH3u','Vintage','','','','','','','','','','','','','',''],
                201:[u'Beat It','PLSRDGXudTSm-smvun7Tmz78xl4KOt5jXQ','Vintage','','','','','','','','','','','','','',''],
                202:[u'Ανθισμένες Βεράντες','PLSRDGXudTSm97IB5s6SRfmPrle5sqyuSj','Vintage','','','','','','','','','','','','','',''],
                203:[u'Ρεμίξ','PLSRDGXudTSm89Z-AwK5F9R32UWuk7sAlQ','Remixes','Monday','','','','','','','','','','','','',''],
                204:[u'Tea Time','PLSRDGXudTSm891XsQ1zOE2K5TRpszLKxL','Remixes','CoffeeLovers','Thursday','','','','','','','','','','','',''],
                205:[u'It\'s Complicated','PLSRDGXudTSm-S8jKpkJMV4_VvKlmI_m72','Remixes','','','','','','','','','','','','','',''],
                206:[u'Second Chance','PLSRDGXudTSm-IbPVIdgdN74OxEIOHNL-v','Remixes','','','','','','','','','','','','','',''],
                207:[u'ReLove','PLSRDGXudTSm8MKzkQ154URg8JpD6XHzyA','Remixes','Melagxolikes','','','','','','','','','','','','',''],
                208:[u'Your Eyes, My Galaxy','PLSRDGXudTSm-l_B-G_ZlUj9cthdZH7FAR','Orchestral','','','','','','','','','','','','','',''],
                209:[u'Νοσταλγία','PLSRDGXudTSm_jW5bLiur5DyM5HmPU4xtL','Orchestral','Sunday','Melagxolikes','','','','','','','','','','','',''],
                210:[u'Χόρεψε Μαζί Μου','PLSRDGXudTSm_hz0sWPa1agA6S2pq9sm-7','Orchestral','','','','','','','','','','','','','',''],
                211:[u'Μελαγχολία','PLSRDGXudTSm-yfS5JUhcPxGq-8pq23WmE','Orchestral','Sunday','Melagxolikes','','','','','','','','','','','',''],
                212:[u'The Sound Of Reading','PLSRDGXudTSm_KDUj_m20QuFIrklAlq60G','Orchestral','BookLovers','Activity','Sunday','','','','','','','','','','',''],
                213:[u'Brain Food','PLSRDGXudTSm90ORXd5mrkr_PnZ8J1F_9s','Orchestral','BookLovers','','','','','','','','','','','','',''],
                214:[u'Soundtracks','PLSRDGXudTSm_IYJHFwQy7bwSZzE3RmZ53','Orchestral','','','','','','','','','','','','','',''],
                215:[u'StuDying','PLSRDGXudTSm_79qlPqL92uqLFxk_5YQeJ','Orchestral','BookLovers','','','','','','','','','','','','',''],
                216:[u'Stress Free','PLSRDGXudTSm9zDvhYyqH95DCms26DfrQn','Orchestral','','','','','','','','','','','','','',''],
                217:[u'Acoustic Love','PLSRDGXudTSm-BGPkb14xzZhDnB-R17BN6','Acoustic','','','','','','','','','','','','','',''],
                218:[u'Μοναξιές','PLSRDGXudTSm8srdhTR8Xuk8sra9hAW3-q','Acoustic','Tuesday','Melagxolikes','','','','','','','','','','','',''],
                219:[u'Deadend Love','PLSRDGXudTSm8qMCdP-pkKguT1VqIGDOki','Acoustic','Wednesday','Melagxolikes','','','','','','','','','','','',''],
                220:[u'Απώλεια','PLSRDGXudTSm8g-htZCKXyk9_i6vJ9LkGZ','Acoustic','Monday','Melagxolikes','','','','','','','','','','','',''],
                221:[u'Κυριακή , Καφές Και Φούτερ','PLSRDGXudTSm_TNZux5Aw816DMgHRbwW1c','CoffeeLovers','RainLovers','Sunday','','','','','','','','','','','',''],
                222:[u'Κυριακάτικα Τραπέζια','PLSRDGXudTSm9DZ9lOizs1Dh0Ez3kD-98R','FoodLovers','LaikesRempetikes','','','','','','','','','','','','',''],
                223:[u'Τσίπουρο Και Λακέρδα','PLSRDGXudTSm_abEPkrA_32jaOhpfxNVcQ','FoodLovers','AlcoholLovers','LaikesRempetikes','','','','','','','','','','','',''],
                224:[u'Ναργιλέδες Και Μπαγλαμάδες','PLSRDGXudTSm9RkBkNLjmQnqASHHwsYFNl','AlcoholLovers','','','','','','','','','','','','','',''],
                225:[u'Drunken Kisses','PLSRDGXudTSm98UGS9RN4SwKn7oKFubyFu','AlcoholLovers','Saturday','','','','','','','','','','','','',''],
                226:[u'Addiction','PLSRDGXudTSm_krCwXF-LLmXXNd1I1wr-n','AlcoholLovers','','','','','','','','','','','','','',''],
                227:[u'Συναυλία Και Μπύρα Κρύα','PLSRDGXudTSm_5fuC5SYTtb7ftAlPJFcTm','AlcoholLovers','','','','','','','','','','','','','',''],
                228:[u'Baby, It\'s Cold Outside','PLSRDGXudTSm8oxXZrZq0QLQZmq34Lj3SV','BedLovers','','','','','','','','','','','','','',''],
                229:[u'Triplove','PLSRDGXudTSm8UDqDNyGHwyJBS5pD4QifI','BedLovers','Wednesday','','','','','','','','','','','','',''],
                230:[u'Bike Ride','PLSRDGXudTSm9lHD5hh0ReiGXJxngtaV1B','TravelLovers','','','','','','','','','','','','','',''],
                231:[u'Sweet Weather','PLSRDGXudTSm9cT51hgQbJODfhj6N5z10z','TravelLovers','','','','','','','','','','','','','',''],
                232:[u'Ευωδιά Της Βρεγμένης Γης','PLSRDGXudTSm8KQ9-jiD1fe0kaVaTwbhFB','RainLovers','Melagxolikes','','','','','','','','','','','','',''],
                233:[u'Rain Shelter','PLSRDGXudTSm9GuXOILgjKiVxSa6QfYa7h','RainLovers','','','','','','','','','','','','','',''],
                234:[u'Άμμος Κι Αρμύρα','PLSRDGXudTSm_lRh1475LeRH-uXKVypyBE','SeaLovers','','','','','','','','','','','','','',''],
                235:[u'Beach Party','PLSRDGXudTSm_4FVnLTrX8pRSjB_DZ5R9K','SeaLovers','','','','','','','','','','','','','',''],
                236:[u'Peaceful Moments','PLSRDGXudTSm8w34dxV7tVLvIrsdVt5Syy','SeaLovers','','','','','','','','','','','','','',''],
                237:[u'Thinking Of You','PLSRDGXudTSm9F116c9fUz4qthOQwGQ5pU','Activity','Melagxolikes','','','','','','','','','','','','',''],
                238:[u'Εκτόνωση','PLSRDGXudTSm-j51SBI3CW__gCS9RPBr2u','Monday','','','','','','','','','','','','','',''],
                239:[u'Blues','PLSRDGXudTSm-mJ4NvHvMJabcg9I0BG3NH','Monday','','','','','','','','','','','','','',''],
                240:[u'Fallen Angel','PLSRDGXudTSm_CnzaH2xC6sCkM1VR0ks6s','Tuesday','Melagxolikes','','','','','','','','','','','','',''],
                241:[u'Jump Around','PLSRDGXudTSm_NP0EyH3ZmQPSqfBtEZYuh','Wednesday','','','','','','','','','','','','','',''],
                242:[u'Future Memories','PLSRDGXudTSm-CCXXyULYQ2Ode-l52n8db','Saturday','','','','','','','','','','','','','',''],
                243:[u'Heartbeat','PLSRDGXudTSm-HH_rZkZWqXCzbhVghnXTQ','Saturday','','','','','','','','','','','','','',''],
                244:[u'I Want You','PLSRDGXudTSm8JuB_76Sg2BVOi5msm6PjU','Sunday','','','','','','','','','','','','','',''],
                245:[u'Bad Desire','PLSRDGXudTSm_QRgfKnGAdKMfIoC66Gjul','Sunday','','','','','','','','','','','','','',''],
                246:[u'Χαρμολύπη','PLSRDGXudTSm9FqSWW7v3EDRaT0I9QFKTC','Melagxolikes','','','','','','','','','','','','','',''],
                247:[u'The End','PLSRDGXudTSm-9_mI7kNRRCdUPClc0ViIL','Melagxolikes','','','','','','','','','','','','','',''],
                248:[u'Χειμώνας','PLSRDGXudTSm8TO1iFRCmUN1CHvrONjYdl','Melagxolikes','','','','','','','','','','','','','',''],
                249:[u'Λύκος','PLSRDGXudTSm_LveR_XK3ECyHHK7ADKHE2','Melagxolikes','','','','','','','','','','','','','',''],
                250:[u'Wait','PLSRDGXudTSm9dNPuQOrtRpwOABIPSf8Lv','Melagxolikes','','','','','','','','','','','','','',''],
                251:[u'Ελιές Κι Αμπέλια','PLSRDGXudTSm_yUv0bGOz-SgqFgR2TMFV8','Entexnes','','','','','','','','','','','','','',''],
                252:[u'Έτσι σ\' αγάπησα','PLSRDGXudTSm_aYrfyTEJwD0otq6n1QFhd','Entexnes','','','','','','','','','','','','','',''],
                253:[u'Χαίνης','PLSRDGXudTSm9JI48T3-5Ci7oqOWqW3h-D','Entexnes','','','','','','','','','','','','','',''],
                254:[u'Βουνά Και Θάλασσες','PLSRDGXudTSm9pw-UNuxoqmaA5vgVXMn9d','Entexnes','','','','','','','','','','','','','',''],
                255:[u'Άγρυπνα Βράδια','PLSRDGXudTSm87J6jeZRNRZlLF9HddJrts','Entexnes','','','','','','','','','','','','','',''],
                256:[u'Ήχοι της Ανατολίας','PLSRDGXudTSm8KT3BazbXqHVjS3YCWT3Mv','Entexnes','','','','','','','','','','','','','',''],
                257:[u'Συναυλία Και Μπύρα Κρύα','PLSRDGXudTSm_5fuC5SYTtb7ftAlPJFcTm','Entexnes','','','','','','','','','','','','','',''],
                258:[u'Πέρασε ο καιρός','PLSRDGXudTSm90fISIBIwSChWHwhSrrSZN','Entexnes','','','','','','','','','','','','','',''],
                259:[u'Τα Μελοποιημένα','PLSRDGXudTSm9QpLLRv6o3qa91ygur8uLf','Entexnes','','','','','','','','','','','','','',''],
                260:[u'Όνειρο','PLSRDGXudTSm_05al3ZZeoZek1ogQ6vZLZ','Entexnes','','','','','','','','','','','','','',''],
                261:[u'Περιπλανήσεις','PLSRDGXudTSm-jMyOtsQHZW7vVm8tY049W','Entexnes','','','','','','','','','','','','','',''],
                262:[u'Παλιά Πληγή','PLSRDGXudTSm_aadb8ewwyg_F_G0peX2qL','Entexnes','','','','','','','','','','','','','',''],
                263:[u'Σιγολιώνω','PLSRDGXudTSm-SAmjJJGekC5SKd3fGqw4a','Entexnes','','','','','','','','','','','','','',''],
                264:[u'Χειμωνανθός','PLSRDGXudTSm9AUt07G0XqAShTEhoZJd81','Entexnes','','','','','','','','','','','','','',''],
                265:[u'Παραμύθι','PLSRDGXudTSm8bCpPo9XPi4HtC1Nyk5r3S&v=lRLycGV79g4','','','','','','','','','','','','','','',''],
                266:[u'Ο Σωκράτης Στου Θανάση','PLSRDGXudTSm_LBOZc8o20qKa3X8Ni-fow','Entexnes','','','','','','','','','','','','','',''],
                267:[u'Λησμονιά','PLSRDGXudTSm8HvtpEO247r10wxDG1B-uo','Entexnes','','','','','','','','','','','','','',''],
                268:[u'Ψυχομαζέματα','PLSRDGXudTSm9ISXfQz9gGTNswikjTKiEB','Entexnes','','','','','','','','','','','','','',''],
                269:[u'Της Μέθης Τα Μεράκια','PLSRDGXudTSm-n6J2Mvwk8Iq3N4HGkxQz2','Entexnes','','','','','','','','','','','','','',''],
                270:[u'Αναστεναγμοί','PLSRDGXudTSm9JdzYGRdzoH-b_ZuCKwGsH','Entexnes','','','','','','','','','','','','','',''],
                271:[u'Κρυφοί Καημοί','PLSRDGXudTSm8Gr9D9YI4Hda7KLE_1qRUy','Entexnes','','','','','','','','','','','','','',''],
                272:[u'Θύμησες','PLSRDGXudTSm-sbIDuubpzkLowIcTCdvTb','Entexnes','','','','','','','','','','','','','',''],
                273:[u'Μόρτισσες Και Μάγκες','PLSRDGXudTSm_A0bYXOg86vBNibUvN4S4A','LaikesRempetikes','','','','','','','','','','','','','',''],
                274:[u'Κανείς Εδώ Δεν Τραγουδά','PLSRDGXudTSm9HuuBPnB9wwkbq_mbenaCf','LaikesRempetikes','','','','','','','','','','','','','',''],
                275:[u'Ντουζένια Και Νταλκάδες','PLSRDGXudTSm8XWVNiwJC_zKpdely5-giV','LaikesRempetikes','','','','','','','','','','','','','',''],
                276:[u'Που \'ναι τα χρόνια ;','PLSRDGXudTSm-blclZ5IAvi3DsqyWybgHM','LaikesRempetikes','','','','','','','','','','','','','',''],
                277:[u'Ναργιλέδες Και Μπαγλαμάδες','PLSRDGXudTSm9RkBkNLjmQnqASHHwsYFNl','LaikesRempetikes','','','','','','','','','','','','','',''],
                278:[u'Τα Λαικά Του Τζουκ Μποξ','PLSRDGXudTSm_MpKTx1ypfsjF0sY6nZ_aa','LaikesRempetikes','','','','','','','','','','','','','',''],
                279:[u'Απόψε Σιωπηλοί','PLSRDGXudTSm_D6i0h4ZGDAOkZMAJ6DTXx','LaikesRempetikes','','','','','','','','','','','','','',''],
                280:[u'Νύχτες Μαγικές','PLSRDGXudTSm8Vj5Ef7-nCjV1dXEcQHOHs','LaikesRempetikes','','','','','','','','','','','','','',''],
                281:[u'Βάλτε Κρασί','PLSRDGXudTSm8xON9PiOcyvX7QGkr9wdUi','LaikesRempetikes','','','','','','','','','','','','','',''],
                282:[u'Η Νύχτα Κατεβαίνει','PLSRDGXudTSm-DplseSXwq5l35ZhkmWYqp','LaikesRempetikes','','','','','','','','','','','','','',''],
                283:[u'Όμορφες Αναμνήσεις','PLSRDGXudTSm8ufA1UCmYllOfkamYza-Wy','Omorfes','','','','','','','','','','','','','',''],
                284:[u'Πάστα Φλώρα','PLSRDGXudTSm8LpCp578T8rhswvPwkk8Mf','Omorfes','','','','','','','','','','','','','',''],
                285:[u'Ντόπιο Ιντερνάσιοναλ','PLSRDGXudTSm8CnkUet97Kdhhxf56479XH','Omorfes','','','','','','','','','','','','','',''],
                286:[u'Αλλιώτικη Μέρα','PLSRDGXudTSm9jKZp0v01uKUnK4ISikblr','Omorfes','','','','','','','','','','','','','',''],
                287:[u'Η Αγάπη Είναι Ζάλη','PLSRDGXudTSm8CrwlTcu1s9P6liayxZ5o2','Omorfes','','','','','','','','','','','','','',''],
                288:[u'Ετοιμάζω Ταξίδι','PLSRDGXudTSm-JpXLiRsQ87LVHYinnzRDG','Omorfes','','','','','','','','','','','','','',''],
                289:[u'Βάλσαμο','PLSRDGXudTSm-Ai_fgh-YIuR9qkr8daVoU','Omorfes','','','','','','','','','','','','','',''],
                290:[u'Σου Σφυρίζω','PLSRDGXudTSm_bZFPDuvxLm5T8LmZl52Ui','Omorfes','','','','','','','','','','','','','',''],
                291:[u'Μπαρ το ναυάγιο','PLSRDGXudTSm_42DTs378ahN8FUivNIEia','Omorfes','','','','','','','','','','','','','',''],
                292:[u'Παιχνίδια Στην Άμμο','PLSRDGXudTSm-kCQe2G9hpeilG4_5djS-j','Omorfes','','','','','','','','','','','','','','']
                # 293:[u'','','','','','','','','','','','','','','','',''],
                # 294:[u'','','','','','','','','','','','','','','','',''],
                # 295:[u'','','','','','','','','','','','','','','','',''],
                # 296:[u'','','','','','','','','','','','','','','','',''],
                # 297:[u'','','','','','','','','','','','','','','','',''],
                # 298:[u'','','','','','','','','','','','','','','','',''],
                # 299:[u'','','','','','','','','','','','','','','','',''],
                # 300:[u'','','','','','','','','','','','','','','','',''],
                # 301:[u'','','','','','','','','','','','','','','','',''],
                # 302:[u'','','','','','','','','','','','','','','','',''],
                # 303:[u'','','','','','','','','','','','','','','','',''],
                # 304:[u'','','','','','','','','','','','','','','','',''],
                # 305:[u'','','','','','','','','','','','','','','','',''],
                # 306:[u'','','','','','','','','','','','','','','','',''],
                # 307:[u'','','','','','','','','','','','','','','','',''],
                # 308:[u'','','','','','','','','','','','','','','','',''],
                # 309:[u'','','','','','','','','','','','','','','','',''],
                # 310:[u'','','','','','','','','','','','','','','','',''],
                # 311:[u'','','','','','','','','','','','','','','','',''],
                # 312:[u'','','','','','','','','','','','','','','','',''],
                # 313:[u'','','','','','','','','','','','','','','','',''],
                # 314:[u'','','','','','','','','','','','','','','','',''],
                # 315:[u'','','','','','','','','','','','','','','','',''],
                # 316:[u'','','','','','','','','','','','','','','','',''],
                # 317:[u'','','','','','','','','','','','','','','','',''],
                # 318:[u'','','','','','','','','','','','','','','','',''],
                # 319:[u'','','','','','','','','','','','','','','','',''],
                # 320:[u'','','','','','','','','','','','','','','','',''],
                # 321:[u'','','','','','','','','','','','','','','','',''],
                # 322:[u'','','','','','','','','','','','','','','','',''],
                # 323:[u'','','','','','','','','','','','','','','','',''],
                # 324:[u'','','','','','','','','','','','','','','','',''],
                # 325:[u'','','','','','','','','','','','','','','','',''],
                # 326:[u'','','','','','','','','','','','','','','','',''],
                # 327:[u'','','','','','','','','','','','','','','','',''],
                # 328:[u'','','','','','','','','','','','','','','','',''],
                # 329:[u'','','','','','','','','','','','','','','','',''],
                # 330:[u'','','','','','','','','','','','','','','','',''],
                # 331:[u'','','','','','','','','','','','','','','','',''],
                # 332:[u'','','','','','','','','','','','','','','','',''],
                # 333:[u'','','','','','','','','','','','','','','','',''],
                # 334:[u'','','','','','','','','','','','','','','','',''],
                # 335:[u'','','','','','','','','','','','','','','','',''],
                # 336:[u'','','','','','','','','','','','','','','','',''],
                # 337:[u'','','','','','','','','','','','','','','','',''],
                # 338:[u'','','','','','','','','','','','','','','','',''],
                # 339:[u'','','','','','','','','','','','','','','','',''],
                # 340:[u'','','','','','','','','','','','','','','','',''],
                # 341:[u'','','','','','','','','','','','','','','','',''],
                # 342:[u'','','','','','','','','','','','','','','','',''],
                # 343:[u'','','','','','','','','','','','','','','','',''],
                # 344:[u'','','','','','','','','','','','','','','','',''],
                # 345:[u'','','','','','','','','','','','','','','','',''],
                # 346:[u'','','','','','','','','','','','','','','','',''],
                # 347:[u'','','','','','','','','','','','','','','','',''],
                # 348:[u'','','','','','','','','','','','','','','','',''],
                # 349:[u'','','','','','','','','','','','','','','','',''],
                # 350:[u'','','','','','','','','','','','','','','','',''],
                # 351:[u'','','','','','','','','','','','','','','','',''],
                # 352:[u'','','','','','','','','','','','','','','','',''],
                # 353:[u'','','','','','','','','','','','','','','','',''],
                # 354:[u'','','','','','','','','','','','','','','','',''],
                # 355:[u'','','','','','','','','','','','','','','','',''],
                # 356:[u'','','','','','','','','','','','','','','','',''],
                # 357:[u'','','','','','','','','','','','','','','','',''],
                # 358:[u'','','','','','','','','','','','','','','','',''],
                # 359:[u'','','','','','','','','','','','','','','','',''],
                # 360:[u'','','','','','','','','','','','','','','','',''],
                # 361:[u'','','','','','','','','','','','','','','','',''],
                # 362:[u'','','','','','','','','','','','','','','','',''],
                # 363:[u'','','','','','','','','','','','','','','','',''],
                # 364:[u'','','','','','','','','','','','','','','','',''],
                # 365:[u'','','','','','','','','','','','','','','','',''],
                # 366:[u'','','','','','','','','','','','','','','','',''],
                # 367:[u'','','','','','','','','','','','','','','','',''],
                # 368:[u'','','','','','','','','','','','','','','','',''],
                # 369:[u'','','','','','','','','','','','','','','','',''],
                # 370:[u'','','','','','','','','','','','','','','','',''],
                # 371:[u'','','','','','','','','','','','','','','','',''],
                # 372:[u'','','','','','','','','','','','','','','','',''],
                # 373:[u'','','','','','','','','','','','','','','','',''],
                # 374:[u'','','','','','','','','','','','','','','','',''],
                # 375:[u'','','','','','','','','','','','','','','','',''],
                # 376:[u'','','','','','','','','','','','','','','','',''],
                # 377:[u'','','','','','','','','','','','','','','','',''],
                # 378:[u'','','','','','','','','','','','','','','','',''],
                # 379:[u'','','','','','','','','','','','','','','','',''],
                # 380:[u'','','','','','','','','','','','','','','','',''],
                # 381:[u'','','','','','','','','','','','','','','','',''],
                # 382:[u'','','','','','','','','','','','','','','','',''],
                # 383:[u'','','','','','','','','','','','','','','','',''],
                # 384:[u'','','','','','','','','','','','','','','','',''],
                # 385:[u'','','','','','','','','','','','','','','','',''],
                # 386:[u'','','','','','','','','','','','','','','','',''],
                # 387:[u'','','','','','','','','','','','','','','','',''],
                # 388:[u'','','','','','','','','','','','','','','','',''],
                # 389:[u'','','','','','','','','','','','','','','','',''],
                # 390:[u'','','','','','','','','','','','','','','','',''],
                # 391:[u'','','','','','','','','','','','','','','','',''],
                # 392:[u'','','','','','','','','','','','','','','','',''],
                # 393:[u'','','','','','','','','','','','','','','','',''],
                # 394:[u'','','','','','','','','','','','','','','','',''],
                # 395:[u'','','','','','','','','','','','','','','','',''],
                # 396:[u'','','','','','','','','','','','','','','','',''],
                # 397:[u'','','','','','','','','','','','','','','','',''],
                # 398:[u'','','','','','','','','','','','','','','','',''],
                # 399:[u'','','','','','','','','','','','','','','','',''],
                # 400:[u'','','','','','','','','','','','','','','','','']

            }
    FinalPlaylist = {}
    counter = 0
    for i in allPlaylists:
        if allPlaylists[i][2] == category or allPlaylists[i][3] == category or allPlaylists[i][4] == category or allPlaylists[i][5]==category or allPlaylists[i][6] == category or allPlaylists[i][7]==category or allPlaylists[i][8]==category:
            counter += 1
            FinalPlaylist[i] = [allPlaylists[i][0], allPlaylists[i][1]]
            FinalPlaylist[counter] = FinalPlaylist.pop(i)
    return FinalPlaylist
